### ISSUE TITLE
I keep getting "Couldn't find TocSigCheck Pattern" when i launch the game

### ISSUE THREAD

**Issue by calebaiello** [thethiny/MK12TTH#1]
I'm not very good at coding stuff but ive tried a couple of things but i cant get it to work.

**Comment by thethiny** [comment]
Are you still getting the same problem?

**Comment by thethiny** [comment]
Stale

**Comment by AymanCad** [comment]
I've always wondered what the error was, and I still see it to this day. Could that be the reason for the intermittent, inexplicable crashes?

**Comment by thethiny** [comment]
Unsure why you're still facing it. Anyway, the crash is unrelated to this, since if this fails then it will skip.
