### ISSUE TITLE
desync

### ISSUE THREAD

**Issue by ghost** [thethiny/MK12TTH#3]
The game is desyncing online when using the 60 fps mod, is there a way to only use it for singeplayer or fix the online issue? I know u can use it for invasion only, but 30fps on menu is horrible. Thanks!

**Comment by raldebsi** [comment]
That is a problem in MK1Hook and not MK12TTH.

**Comment by thethiny** [comment]
Hi @Lucifer21121. I think you're confusing my Mod Loader (MK12TTH) with ermaccer's MK1Hook.
